cache:
  build: ./cache/

logs:
  build: ./logs/

fez:
  build: ./backend/nginx/
  links:
    - fpm
  ports:
    - "8080:80"
  volumes_from:
    - fpm
    - cache
    - fedoradata
    - logs

fpm:
  build: ./backend/fpm/
  environment:
    - APP_ENVIRONMENT=development
    - XDEBUG_CONFIG=idekey=fez
    - PHP_IDE_CONFIG=serverName=dev-fez.library.uq.edu.au
    - JAVA_HOME=/usr/lib/jvm/jre
    - JHOVE_HOME=/usr/local/jhove
  hostname: dev-fez.library.uq.edu.au
  links:
    - fezdb
    - fedora
    - fedoradb
    - solr
  volumes:
    - ../../:/var/app/current
  volumes_from:
    - cache
    - fedoradata
    - logs

fezdb:
  build: ./backend/db/
  environment:
    - MYSQL_ROOT_PASSWORD=development
    - MYSQL_USER=fez
    - MYSQL_PASSWORD=fez
    - MYSQL_DATABASE=fez
  ports:
    - "3306:3306"
  volumes:
    - data/mysql/fezdb:/var/lib/mysql
  volumes_from:
    - logs

fedora:
  build: ./fedora/
  links:
    - fedoradb
  ports:
    - "10081:10081"
    - "10082:10082"
  privileged: true
  volumes_from:
    - fedoradata
    - logs

fedoradata:
  build: ./fedora/data/
  volumes:
    - /data/docker/fez/fedora:/espace/data
    - /data/docker/fez/espace_san:/espace_san

fedoradb:
  build: ./fedora/db/
  environment:
    - MYSQL_ROOT_PASSWORD=development
    - MYSQL_USER=fedoraAdmin
    - MYSQL_PASSWORD=fedoraAdmin
    - MYSQL_DATABASE=fedora3
  ports:
    - "3307:3306"
  privileged: true
  volumes:
    - data/mysql/fedoradb:/var/lib/mysql
  volumes_from:
    - logs

solr:
  build: ./solr/
  ports:
    - "8983:8983"
  volumes:
    - data/solr:/var/lib/solr
  volumes_from:
    - cache
    - logs
