cache:
  build: ./cache/

logs:
  build: ./logs/

backend:
  build: ./backend/
  environment:
    - APP_ENVIRONMENT=development
    - XDEBUG_CONFIG=idekey=fez
    - PHP_IDE_CONFIG=serverName=dev-fez.library.uq.edu.au
    - JAVA_HOME=/usr/lib/jvm/jre
    - JHOVE_HOME=/usr/local/jhove
  links:
    - fezdb
    - fedora
    - fedoradb
    - solr
  ports:
    - "8080:8080"
      privileged: true
  volumes:
    - ../../:/var/app/current
  volumes_from:
    - cache
    - fedoradata
    - logs

fezdb:
  build: ./backend/db/
  environment:
    - MYSQL_ROOT_PASSWORD=development
    - MYSQL_USER=fez
    - MYSQL_PASSWORD=fez
    - MYSQL_DATABASE=fez
  ports:
    - "3306:3306"
  volumes_from:
    - fezdbdata
    - logs

fezdbdata:
  build: ./backend/db/data/

fedora:
  build: ./fedora/
  links:
    - fedoradb
  ports:
    - "10081:10081"
    - "10082:10082"
  privileged: true
  volumes_from:
    - fedoradata
    - logs

fedoradata:
  build: ./fedora/data/
  volumes:
    - /data/docker/fez/fedora:/espace/data

fedoradb:
  build: ./fedora/db/
  environment:
    - MYSQL_ROOT_PASSWORD=development
    - MYSQL_USER=fedoraAdmin
    - MYSQL_PASSWORD=fedoraAdmin
    - MYSQL_DATABASE=fedora3
  ports:
    - "3307:3306"
  privileged: true
  volumes_from:
    - fedoradbdata
    - logs

fedoradbdata:
  build: ./fedora/db/data/

solr:
  build: ./solr/
  ports:
    - "8983:8983"
  volumes_from:
    - cache
    - solrdata
    - logs

solrdata:
  build: ./solr/data/
